### ISSUE TITLE
1. As a component, I want to be able to read from and write to the Firestore database so that users can persist information.

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-15-smart-shopping-list#1]
This is 1 of 2 stories that should be completed in the first week to enable further development of the app.

AC:

* The following have been added as project dependencies: `firebase` & `react-firestore`
* Make a change in the Firestore database and it shows up in the app
* Make a change in the app and it shows up in the Firestore database

**Comment by segdeha** [comment]
Reminder: Keep this simple. Maybe just a counter button or something 🙂
