### ISSUE TITLE
2. As a user, I want to be able to navigate between the “list” view and the “add an item” view so that the interface is clearly delinteated between viewing and adding.

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-15-smart-shopping-list#2]
This is 1 of 2 stories that should be completed in the first week to enable further development of the app.

AC:

* `react-router-dom` has been added as a project dependency
* Links are present and persistent at the bottom of the app: one for the “list” view, the other for the “add an item” view
* When one of the links is clicked, the browser URL updates to represent the current view and a matching view component is displayed
* Whichever view is selected, the corresponding link should display in bold text

**Comment by segdeha** [comment]
Reminder: Keep styling super simple at this point. There will be time to add more styling later in the project 👍
